### ISSUE TITLE
【JSDoc 作成】TableHeader.tsx

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer#60]

**Comment by tsukimi0618** [comment]
> react@0.0.0 dev
> vite


  VITE v5.3.5  ready in 213 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.112.3:3000/

> react@0.0.0 dev
> vite


  VITE v5.3.5  ready in 201 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.112.3:3000/

> react@0.0.0 dev
> vite


  VITE v5.3.5  ready in 224 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.112.3:3000/
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /usr/src/app): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
    at load (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33551:11)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33576:16
    at Array.map (<anonymous>)
    at plugins (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33575:8)
    at processResult (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33645:14)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33775:14]

Node.js v20.16.0
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /usr/src/app): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
    at load (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33551:11)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33576:16
    at Array.map (<anonymous>)
    at plugins (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33575:8)
    at processResult (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33645:14)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33775:14]

Node.js v20.16.0
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /usr/src/app): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /usr/src/app/postcss.config.js

(@/usr/src/app/postcss.config.js)
    at load (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33551:11)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33576:16
    at Array.map (<anonymous>)
    at plugins (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33575:8)
    at processResult (file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33645:14)
    at file:///usr/src/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:33775:14]

Node.js v20.16.0

**Comment by tsukimi0618** [comment]
PR作成しました。
https://github.com/RyosukeSakakibara718/project-balancer/pull/99
